
(define (problem pacmanCOMPETICAOTOP)
    (:domain pacman)
    (:objects
        x1 x2 x3 x4 x5 y1 y2 y3 y4 y5 y6 y7 y8 - posicao
    )
    (:init
        (pacman-liberado)
        (parede-em x1 y1)
        (parede-em x2 y1)
        (parede-em x3 y1)
        (parede-em x4 y1)
        (parede-em x5 y1)
        (parede-em x1 y2)
        (pacman-em x2 y2)
        (parede-em x5 y2)
        (parede-em x1 y3)
        (parede-em x3 y3)
        (parede-em x5 y3)
        (parede-em x1 y4)
        (fantasmaG-em x4 y4)
        (parede-em x5 y4)
        (parede-em x1 y5)
        (frutaG-em x2 y5)
        (parede-em x3 y5)
        (parede-em x5 y5)
        (parede-em x1 y6)
        (frutaR-em x3 y6)
        (parede-em x5 y6)
        (parede-em x1 y7)
        (fantasmaR-em x4 y7)
        (parede-em x5 y7)
        (parede-em x1 y8)
        (parede-em x2 y8)
        (parede-em x3 y8)
        (parede-em x4 y8)
        (parede-em x5 y8)
        (fantasmaR-right)
        (inc x1 x2)
        (inc x2 x3)
        (inc x3 x4)
        (inc x4 x5)
        (inc y1 y2)
        (inc y2 y3)
        (inc y3 y4)
        (inc y4 y5)
        (inc y5 y6)
        (inc y6 y7)
        (inc y7 y8)
        (dec x2 x1)
        (dec x3 x2)
        (dec x4 x3)
        (dec x5 x4)
        (dec y2 y1)
        (dec y3 y2)
        (dec y4 y3)
        (dec y5 y4)
        (dec y6 y5)
        (dec y7 y6)
        (dec y8 y7)
    )
    (:goal
        (and
            (not(pacman-morto))
            (fantasmaR-morto) (fantasmaG-morto))
    )
)