
(define (problem pacmanCOMPETICAOTOP)
    (:domain pacman)
    (:objects
        x1 x2 x3 x4 x5 x6 x7 x8 y1 y2 y3 y4 y5 y6 y7 - posicao
    )
    (:init
        (fantasmaR-right)
        (portal-em x7 y2)
        (portal-em x2 y6)
        (portal-link x2 y6 x7 y2)
        (portal-link x7 y2 x2 y6)
        (turno-pacman)
        (parede-em x1 y1)
        (parede-em x2 y1)
        (parede-em x3 y1)
        (parede-em x4 y1)
        (parede-em x5 y1)
        (parede-em x6 y1)
        (parede-em x7 y1)
        (parede-em x8 y1)
        (parede-em x1 y2)
        (pacman-em x2 y2)
        (parede-em x8 y2)
        (parede-em x1 y3)
        (parede-em x8 y3)
        (parede-em x1 y4)
        (frutaG-em x5 y4)
        (frutaB-em x6 y4)
        (frutaR-em x7 y4)
        (parede-em x8 y4)
        (parede-em x1 y5)
        (parede-em x5 y5)
        (parede-em x6 y5)
        (parede-em x7 y5)
        (parede-em x8 y5)
        (parede-em x1 y6)
        (fantasmaB-em x5 y6)
        (fantasmaG-em x6 y6)
        (fantasmaR-em x7 y6)
        (parede-em x8 y6)
        (parede-em x1 y7)
        (parede-em x2 y7)
        (parede-em x3 y7)
        (parede-em x4 y7)
        (parede-em x5 y7)
        (parede-em x6 y7)
        (parede-em x7 y7)
        (parede-em x8 y7)
        (fantasmaR-right)
        (inc x1 x2)
        (inc x2 x3)
        (inc x3 x4)
        (inc x4 x5)
        (inc x5 x6)
        (inc x6 x7)
        (inc x7 x8)
        (inc y1 y2)
        (inc y2 y3)
        (inc y3 y4)
        (inc y4 y5)
        (inc y5 y6)
        (inc y6 y7)
        (dec x2 x1)
        (dec x3 x2)
        (dec x4 x3)
        (dec x5 x4)
        (dec x6 x5)
        (dec x7 x6)
        (dec x8 x7)
        (dec y2 y1)
        (dec y3 y2)
        (dec y4 y3)
        (dec y5 y4)
        (dec y6 y5)
        (dec y7 y6)
    )
    (:goal
        (and
            (not(pacman-morto))
            (fantasmaR-morto) (fantasmaG-morto) (fantasmaB-morto))
    )
)